### ISSUE TITLE
B27 / B28_InstantMeshesRemesh.py addon not avaiable

### ISSUE THREAD

**Issue by RegulusFen** [knekke/blender_addons#11]
No clue whats going on, I manually install addons all the time but cannot get either B27 nor B28 to come up in 2.79 or 2.83 addon options, I have manually put the .py in the addon folder (%appdata%) and also installed via blenders interface no joy.

Am I missing something?

Thanks

**Comment by knekke** [comment]
could you solve your issue?

**Comment by RegulusFen** [comment]
Thank you for responding, no I never did get the issue sorted out, I have since moved on though, I just use the stand alone Insta-meshes program - Thank you very much!

**Comment by knekke** [comment]
Alright. and sorry for replying that late. In case you want to give it another try:
C:\Users\<YOURUSERNAME>\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons is the location where you should put the .py file, which seems to be exactly what you were doing...
Then it should show up in the Addons-section inside Blender as "Object: Instant Meshes Remesh"  ... if it doesn't and no errors show up in the console, I really have no idea what could be wrong :/
