### ISSUE TITLE
Blender 4.0 Support

### ISSUE THREAD

**Issue by IntOverflow-maxwell** [knekke/blender_addons#13]
This is a bit like necroposting, (sorry), but the current version of B28_InstantMeshesRemesh.py is outdated for the Blender 4.0 python API, where they changed the export and import methods for .obj files. I tried to fix it with the new bpy.ops.wm.obj_export() function, and I didn't really succeed (the object materials and stuff were messed up). So I'm opening this issue. Sorry if I come off arrogant, English isn't exactly my first language!

**Comment by knekke** [comment]
Hi, I had the same problem a couple of days ago and just forgot to update it here. There is a new file now B40_InstantMeshesRemesh.py which should do the trick. Not thoroughly tested, so let me know how it goes.
