### ISSUE TITLE
Instant Meshes Remesh: AttributeError: 'Object' object has no attribute 'hide_viewport'

### ISSUE THREAD

**Issue by Mnc2g** [knekke/blender_addons#6]
Hello,
I get that error just after checking "Start Remeshing".
Could you provide any help?
Blender 2.8, build date: 2019-05-10
Thank you very much!

**Comment by knekke** [comment]
I just tested with todays buildbot version and it works for me. But I just noticed that there has been a change in the API that has been reverted 2 days ago, so todays build might fix it for you, too.
https://developer.blender.org/rB5f84e2d732c22969c79abf244e59e2c8f5eeedb6

**Comment by Mnc2g** [comment]
Hi, thank you very much! Indeed, it works!
