### ISSUE TITLE
Crash when trying to create remesh with more than roughly 200k faces

### ISSUE THREAD

**Issue by ssnd292** [knekke/blender_addons#8]
Hey, love this little addon, but I found it crashing if I want to remesh a model with more than about 200k faces.

Is this intended?

Using Blender v2.81.16 and latest of both Instantmeshes and your Script.

**Comment by knekke** [comment]
Hi, is there some error message? Does it also crash in UI mode? Does Instantmesh also crash if you load your model manually? Is it a specific model that is crashing, or does it always crash with a certain polycount?

**Comment by ssnd292** [comment]
Hey!

> Hi, is there some error message? 

Nope, simply CTD

> Does it also crash in UI mode?

I'm starting it from Blender itself, should have said that I am using B28_InstantMeshesRemesh.py (its a great tool btw!)

> Does Instantmesh also crash if you load your model manually?

Nope, all fine there.

> Is it a specific model that is crashing, or does it always crash with a certain polycount?

It crashes always when I want to enter anything over roughly 200k faces. I have not put time into finding the exact number, but if you'd like I can do.

**Comment by knekke** [comment]
could you provide a .blend with some object that causes a crash?

**Comment by ssnd292** [comment]
Sure, here you go:

[DebugInstantMeshes.zip](https://github.com/knekke/blender_addons/files/4256125/DebugInstantMeshes.zip)

**Comment by knekke** [comment]
mmhhh... working right out of the box on my end. which os are you on?

![image](https://user-images.githubusercontent.com/2271378/75689545-a8d14b00-5ca1-11ea-9e81-0bf09e40903a.png)

**Comment by ssnd292** [comment]
I think I didnt really express myself well enough:
I have a highpoly model with n-faces but I want to remesh it with more than 200.000 faces as the final result. This is when it was usually crashing for me.

**Comment by knekke** [comment]
I just tried with vertex-count set to 50000 which seems to be the max (?) and it results in close to 200k faces without crash. If the standalone works for you, make sure that the commandline version of InstantMesh also works without crashing, because this is what my script is using.

![image](https://user-images.githubusercontent.com/2271378/75972906-8e32e800-5ed4-11ea-9133-7ebf2c2d5cfb.png)
